import { defineConfig, createLogger } from 'vite';
import vue from '@vitejs/plugin-vue';
import builtins from 'builtin-modules';
import { dirname, resolve } from 'path';
import fs from 'node:fs';

// package.json 已声明 "type": "module"，配置按 ESM 加载：
// 禁用 require 与 __dirname，统一用 import fs / import.meta.dirname

// Obsidian 插件要求 main.js 与 manifest.json 同级，outDir 必须指向项目根；
// 已设置 emptyOutDir: false 不会清空目录，此场景下 Vite 的 outDir 警告属于误报，过滤之。
const logger = createLogger();
const filterOutDirWarning = (original: (msg: string, ...rest: any[]) => void) => {
    return (msg: string, ...rest: any[]) => {
        if (msg.includes('build.outDir must not be the same directory')) {
            return;
        }
        original(msg, ...rest);
    };
};
logger.warn = filterOutDirWarning(logger.warn);
logger.warnOnce = filterOutDirWarning(logger.warnOnce);

// /*! 前缀让 terser 保留此注释（Vite 8 中 terser 以 renderChunk 运行，会剥离普通注释）
const banner = `/*!
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 自定义插件来处理相对路径的 .vue 文件导入
function resolveVueImports() {
    return {
        name: 'resolve-vue-imports',
        resolveId(source: string, importer: string) {
            if (source.endsWith('.vue') && !source.startsWith('.') && !source.startsWith('/')) {
                const importerDir = dirname(importer);
                const resolved = resolve(importerDir, source);
                return resolved;
            }
            return null;
        }
    };
}

// 自定义插件来移除 fs 和 path 等 Node.js 内置模块的引用
function removeNodeJsModules() {
    const emptyModuleCode = `
        // Empty module stub for Node.js built-in modules
        // These modules are not available in browser/Obsidian environment
        const emptyStub = {};
        emptyStub.readFileSync = () => new Uint8Array();
        emptyStub.readSync = () => 0;
        emptyStub.existsSync = () => false;
        export default emptyStub;
    `;

    return {
        name: 'remove-nodejs-modules',
        resolveId(source: string) {
            // 将 fs, path, crypto 等模块解析为虚拟 ID
            const nodeModules = ['fs', 'path', 'crypto', 'os', 'util', 'stream', 'buffer'];
            if (nodeModules.includes(source)) {
                return { id: source, external: false };
            }
            return null;
        },
        load(id: string) {
            // 为这些模块返回空内容
            const nodeModules = ['fs', 'path', 'crypto', 'os', 'util', 'stream', 'buffer'];
            if (nodeModules.includes(id)) {
                return emptyModuleCode;
            }
            return null;
        },
        transform(code: string, id: string) {
            // 在转换阶段，处理源代码中的 require 调用
            if (id.includes('node_modules')) {
                let modifiedCode = code;

                // 替换 require('fs'), require('path'), require('crypto')
                modifiedCode = modifiedCode.replace(
                    /require\(["']fs["']\)/g,
                    '({ readFileSync: () => new Uint8Array(), readSync: () => 0, existsSync: () => false })'
                );
                modifiedCode = modifiedCode.replace(
                    /require\(["']path["']\)/g,
                    '({ basename: (s) => s, dirname: (s) => s, join: (...args) => args.join("/") })'
                );
                modifiedCode = modifiedCode.replace(
                    /require\(["']crypto["']\)/g,
                    '({})'
                );

                if (modifiedCode !== code) {
                    return { code: modifiedCode, map: null };
                }
            }
            return null;
        }
    };
}

export default defineConfig(({ mode }) => {
    const isProd = mode === 'production';
    const root = import.meta.dirname;

    return {
        logLevel: 'info',
        customLogger: logger,
        define: {
            // 替换 process.env.NODE_ENV，避免移动端报 "process is not defined" 错误
            'process.env.NODE_ENV': JSON.stringify(mode),
        },
        resolve: {
            alias: {
                '@': resolve(root, 'src'),
                '@dict': resolve(root, 'src/dictionary'),
                '@comp': resolve(root, 'src/component'),
            },
            extensions: ['.ts', '.tsx', '.js', '.jsx', '.vue', '.json']
        },
        plugins: [
            removeNodeJsModules(),  // 必须在最前面，先处理 Node.js 模块
            vue(),
            resolveVueImports(),
            {
                name: 'copy-wasm-file',
                writeBundle() {
                    const srcPath = './node_modules/sql.js/dist/sql-wasm.wasm';
                    const destPath =  './sql-wasm.wasm';
                    if (fs.existsSync(srcPath)) {
                        fs.copyFileSync(srcPath, destPath);
                    }
                }
            },
        ],
        build: {
            outDir: './',
            emptyOutDir: false,
            sourcemap: false,
            minify: isProd ? 'terser' : false,
            target: 'es2016',
            terserOptions: {
                compress: {
                    // 移除 console.*
                    drop_console: isProd,
                    // 移除死代码（如 if (false) { ... }）
                    dead_code: true,
                    // 移除调试器
                    drop_debugger: isProd,
                    // 移除条件判断中的常量
                    conditionals: true,
                    // 移除未使用的代码
                    unused: true,
                },
            },
            // 禁用压缩时的静态资源内联
            assetsInlineLimit: 0,
            lib: {
                entry: './src/main.ts',
                name: 'LanguageLearner',
                // package.json "type": "module" 下 Vite 会把 cjs 产物命名为 main.cjs，
                // 而 Obsidian 只加载 main.js，必须显式固定文件名
                fileName: () => 'main.js',
                formats: ['cjs']
            },
            rollupOptions: {
                treeshake: true,
                external: [
                    'obsidian',
                    'electron',
                    '@codemirror/autocomplete',
                    '@codemirror/closebrackets',
                    '@codemirror/collab',
                    '@codemirror/commands',
                    '@codemirror/comment',
                    '@codemirror/fold',
                    '@codemirror/gutter',
                    '@codemirror/highlight',
                    '@codemirror/history',
                    '@codemirror/language',
                    '@codemirror/lint',
                    '@codemirror/matchbrackets',
                    '@codemirror/panel',
                    '@codemirror/rangeset',
                    '@codemirror/rectangular-selection',
                    '@codemirror/search',
                    '@codemirror/state',
                    '@codemirror/stream-parser',
                    '@codemirror/text',
                    '@codemirror/tooltip',
                    '@codemirror/view',
                    'fs',  // 显式排除 fs 模块，防止 sql.js 打包时引入
                    'path', // path 模块也需要排除
                    ...builtins],
                output: {
                    exports: 'auto',
                    banner,
                    globals: {
                        'obsidian': 'obsidian'
                    },
                    assetFileNames: (assetInfo) => {
                        // 将所有 CSS 文件统一命名为 styles.css
                        if (assetInfo.name && assetInfo.name.endsWith('.css')) {
                            return 'styles.css';
                        }
                        // 其他资源保持原名称
                        return assetInfo.name;
                    }
                }
            }
        },
        css: {
            devSourcemap: !isProd
        },
        // public 目录配置 - 禁用自动复制 public 目录文件
        // Obsidian 插件会手动管理资源文件
        publicDir: false
    };
});
